% SPDX-FileCopyrightText: Copyright (c) 2022-2024 Bruna Campos
% SPDX-License-Identifier: GPL-3.0-or-later

function [coords, conn] = LoadMesh(meshfile, nsd, config_dir)
% Load mesh data from a mesh file generated by GMSH
% Acknowledgements: Matin Parchei Esfahani

filename = fullfile(config_dir, meshfile);
fileID = fopen(filename,'r');

s = textscan(fileID, '%s', 'delimiter', '\n');

% start of nodes section
n_str = find(strcmp(s{1}, '$Nodes'), 1, 'first');       
% start of elements section
e_str = find(strcmp(s{1}, '$Elements'), 1, 'first');    

% number of nodes
nnode = str2double( s{1}(n_str+1) );                   
% number of elements
nelem = str2double( s{1}(e_str+1) );                    

coords = zeros(nnode, nsd);

for i = 1:nnode
    temp = s{1}(n_str+1+i);
    temp = sscanf(temp{1}(1,:), '%f');
    % nodal coordinates
    coords(i,:) = temp(2:nsd+1)';                        
end

conn = [];

for i = 1:nelem
    temp = s{1}(e_str+1+i);
    temp = sscanf(temp{1}(1,:), '%d');
    % equivalent type number in GMSH
    elmtyp = temp(2);                                  

    switch elmtyp
        case 5          % B8
            nne = 8;
            if nsd == 3
                edg = 0;
            else
                edg = 1;
            end
        case 1          % L2
            nne = 2;    % number of nodes per element
            if nsd == 1
                edg = 0;
            else
                edg = 1;
            end
        case 8          % L3
            nne = 3;    % number of nodes per element
            edg = 1;
        case 3          % Q4
            nne = 4;    % number of nodes per element
            if nsd == 2
                edg = 0;
            else
                edg = 1;
            end
        case 10         % Q9
            nne = 9;    % number of nodes per element
            if nsd == 2
                edg = 0;
            else
                edg = 1;
            end
        case 15         % single node element
            nne = 1;    % number of nodes per element
            edg = 1;    
        case 12         % B27
            nne = 27;   % number of nodes per element
            if nsd == 3
                edg = 0;
            else
                edg = 1;
            end
        case 2          % T3 element
            nne = 3;
            if nsd == 2
                edg = 0;
            else
                edg = 1;
            end
        case 9          % T6 element
            nne = 6;    
            if nsd == 2
                edg = 0;
            else
                edg = 1;
            end
    end
    
    if ~edg
        conn = [conn; temp(end-nne+1:end)'];
    end
    
end

clear s
fclose(fileID);

end