name: Protect CODEOWNERS file

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  protect-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CODEOWNERS was modified
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data.number,
              }
            );
            const changed = files.some(f =>
              f.filename === '.github/CODEOWNERS' || f.filename === 'CODEOWNERS'
            );
            if (changed) {
              core.setFailed('🚫 Pull request modifies the CODEOWNERS file. Only the repository owner may do this.');
            } else {
              console.log('✅ CODEOWNERS file not modified.');
            }
